const events = [
  {
    institution: "RocketSeat",
    image: "./assets/rocketseat.png",
    events: [
      {
        name: "NLW Pocket Javascript",
        hours: "5",
        period: "09/09/24 - 13/09/24",
        req: [
          "Back-end",
          "Node.js",
          "API Rest",
          "TypeScript",
          "Fastify",
          "DrizzleORM",
          "PostgreSQL",
          "Docker",
          "Front-end",
          "ReactJS",
          "TailwindCSS",
          "TanStack Query",
        ],
      },
      {
        name: "NLW Connect: Node.Js",
        hours: "5",
        period: "09/09/24 - 13/09/24",
        req: [
          "Back-end",
          "Node.js",
          "API Rest",
          "TypeScript",
          "Fastify",
          "DrizzleORM",
          "PostgreSQL",
          "Docker",
          "Redis",
          "Zod",
          "Swagger",
        ],
      },
      {
        name: "NLW Pocket Mobile: React Native",
        hours: "5",
        period: "09/12/24 - 13/12/24",
        req: ["React Native", "TypeScript", "Expo Framework", "Expo Router"],
      },
      {
        name: "NLW Connect: React",
        hours: "5",
        period: "09/09/24 - 13/09/24",
        req: [
          "Front-end",
          "ReactJS",
          "NextJS",
          "TailwindCSS",
          "React Hook Form",
          "Orval",
          "Biome",
          "Typescript",
        ],
      },
    ],
  },
  {
    institution: "Alura",
    image: "./assets/alura.png",
    events: [
      {
        name: "Imersão Dev",
        hours: "4",
        period: "Finalizado em 16/09/24",
        req: ["HTML", "CSS", "JavaScript", "IA com Google"],
      },
      {
        name: "Imersão Back-End",
        hours: "4",
        period: "Finalizado em 03/12/24",
        req: [
          "JavaScript",
          "Node.js",
          "API Rest",
          "Express.js",
          "MongoDB",
          "FireBase",
        ],
      },
    ],
  },
  {
    institution: "Cod3r",
    image: "./assets/cod3r.png",
    events: [
      {
        name: "Formação DEV",
        hours: "7",
        period: "Finalizado em 03/10/24",
        req: [
          "Back-end",
          "NestJs",
          "TypeScript",
          "PostgreSQL",
          "Docker",
          "Prisma",
          "Front-end",
          "ReactJS",
          "TailwindCSS",
          "Zod",
          "NextJS",
          "TailwindCSS",
          "React Hook Form",
        ],
      },
    ],
  },
];
